### ISSUE TITLE
running flexdashboard cell in rcloud creates frankenpage

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.flexdashboard#7]
Here's a fun one! Running a cell which contains code marked as flexdashboard causes flexdashboard to take over the layout of RCloud but keep much of the RCloud content, leading to a bizarre mixture of apps. 

![image](https://cloud.githubusercontent.com/assets/1366709/19976989/5397bb16-a1c8-11e6-8fa4-70fede58ae40.png)

I just created the default flexdashboard example in RStudio, added some plots, and then copy/pasted the code to RCloud and ran it.

Personally, I love this kind of mess, but we should probably not allow this - might require changes to [rcloud.rmarkdown](https://github.com/att/rcloud/tree/develop/rcloud.packages/rcloud.rmarkdown) to strip existing YAML configuration or screen out stuff that won't work.

The mess is bizarrely well-integrated, probably because both use Bootstrap.

**Comment by gaborcsardi** [comment]
I don't think this has much to do with `rcloud.flexdashboard`, actually. `rcloud.flexdashboard` only runs code on the special `flexdashboard.html` page, not in the notebook.

Btw. the "proper" way to import an Rmd is using the `rcloud.rmd` package. This will create multiple cells, in a notebook that you can run, without getting this mess.

But sure, it does look impressive. :)

**Comment by gordonwoodhull** [comment]
So rcloud.flexdashboard is not designed to work with plain RMarkdown cells?

The expected use for this one is to create dashboards within RCloud, not so much to import them.

**Comment by gaborcsardi** [comment]
You mean 'rmarkdown' cell type? Then no. Having a whole dashboard in a single cell is not really practical imo.

If you import the Rmd, then each code chunk will be in its own cell, and then you can run the notebook.

`flexashboard.html` could handle your case with minimal modifications, though, so I'll "fix" this.

But I am afraid I can't help you within the notebook.

**Comment by gordonwoodhull** [comment]
Yeah, this is a bug on rcloud.rmarkdown - I'll open it over there. 

I would hope that rcloud.flexdashboard would handle R chunks within markdown and Rmarkdown cells just as well as R cells - is that difficult? I thought it was just concatenating everything.

**Comment by gaborcsardi** [comment]
I would not encourage Rmarkdown cells, because they are inconvenient, you cannot run them in the notebook. (Unless you like frankenpages.) Rmd import does not create rmarkdown cells, and I think we should discourage people from creating them as well.

Currently `flxdashoard.html` is concatenating `md` and `R` cells. Sure, `Rmd` cells could be included, but again, and `Rmd` cells are _full_ Rmd documents, so ideally they should not be part of other Rmd documents.

**Comment by gordonwoodhull** [comment]
RMarkdown cells are usually translated into HTML **fragments**. There's nothing inherently unsafe about that. 

They just use the RMarkdown stack for rendering instead of knitr directly. And apparently they don't protect against clumsy users pasting in YAML that overrides the render type. :wink:

**Comment by gaborcsardi** [comment]
> There's nothing inherently unsafe about that.

Well, you still got a frankenpage..... even if they are just HTML, they should be put in an iframe I think, so that they don't change the layout of the whole page.

Ans it really does not make any sense to use them in an Rmd/flexdashboard imo. I think they will just cause confusion without adding any benefit.
